<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>async và await</title>
</head>

<body>
    <script>
        // asysnc await là cú pháp giúp cho việc sử dụng promise trở nên dễ đọc hơn
        // tránh trường hợp promise lồng vào nhau.

        // sử dụng từ khóa async trước function để sử dụng, nó luôn trả về promise
        // khi dùng từ khóa await bắt buộc phải dùng hàm khai báo bằng async.

        // mỗi khi sử dụng từ khóa await sẽ thay cho việc ta phải sử dụng .then
        // so sánh với ví dụ sử dụng promise thông thường ở bên dưới.

        // khi sử dụng .then là thực hiện bất đồng bộ kết quả phía sau phụ thuộc vào
        // kết quả phía trước, nếu kết quả trước sảy ra lỗi thì kết quả phía sau vẫn được chạy
        // await được hiểu tương tự như .then

        // ví dụ sử dụng async await
        const getNewTodo = async () => {
            try {

                // khi sử dụng async await thì thực hiện sử lý lỗi bằng try catch nếu try sảy ra lỗi sẽ lọt vào catch
                // còn với promise khi sảy ra lỗi ở reject() thì thì lỗi sẽ nhảy vào .catch
                let response = await fetch('https://jsonplaceholder.typicode.com/posts');
                let data = await response.json();
                return data;
            } catch (error) {
                console.error('Error fetching data:', error);

                // sử dụng throw để ném ra ngoại lệ
                throw error;
            }
        };

        getNewTodo()
            .then(data => {
                console.log(data);
            })
            .catch(error => {
                console.error('An error occurred:', error);
            });


        // ví dụ sử dụng promise truyền thống
        const getNewTodo2 = function () {
            return new Promise((resolve, reject) => {
                fetch('https://jsonplaceholder.typicode.com/posts')
                    .then(response => response.json())
                    .then(data => {
                        resolve(data);
                    })
                    .catch(error => {
                        reject(error);
                    });
            });
        };

        getNewTodo2()
            .then(data => {
                console.log(data);
            })
            .catch(error => {
                console.error('An error occurred:', error);
            });
    </script>
</body>

</html>